version: "2.0"
volumes:
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${MONGO_VOLUME_PATH:-C:\Users\Tatyana\Desktop\Game Lands\deploy\mongo\data}
  postgresql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${POSTGRES_VOLUME_PATH:-C:\Users\Tatyana\Desktop\Game Lands\deploy\postgresql\data}
services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
      - ${MONGO_INIT_PATH:-C:\Users\Tatyana\Desktop\Game Lands\deploy\mongo\init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js}
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    environment:
      - MONGO_INITDB_DATABASE=game-lands
  postgresql:
    image: postgres:12
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: game-lands
      POSTGRES_USER: game-lands
      POSTGRES_DB: game-lands
      PGDATA: /var/lib/postgresql/data/db-files/
    ports:
      - 5432:5432

  land-management-serivce:
    image: game-lands/game-lands-service:0.0.2
    ports:
    - "5000:5000"
    environment:
      POSTGRES_DSN: postgresql://game-lands:game-lands@postgresql:5432/game-lands


  resource-management-serivce:
    image: game-lands/game-resources-service:0.0.2
    ports:
    - "5001:5001"
    environment:
      POSTGRES_DSN: postgresql://game-lands:game-lands@postgresql:5432/game-lands


  building-management-serivce:
    image: game-lands/game-buildings-service:0.0.2
    ports:
    - "5002:5002"
    environment:
      POSTGRES_DSN: postgresql://game-lands:game-lands@postgresql:5432/game-lands         

  
  gameplay-configuration-manager:
    image: game-lands/gameplay-configuration-manager:0.0.2
    ports:
    - "5003:5003"
    environment:
      POSTGRES_DSN: postgresql://game-lands:game-lands@postgresql:5432/game-lands  


  resource-harvesting-service:
    image: game-lands/resource-harvesting-service:0.0.2
    ports:
    - "5004:5004"
    environment:
      POSTGRES_DSN: postgresql://game-lands:game-lands@postgresql:5432/game-lands    


  user-service:
    image: game-lands/user-service:0.0.2
    ports:
    - "5005:5005"
    environment:
      POSTGRES_DSN: postgresql+asyncpg://game-lands:game-lands@postgresql:5432/game-lands      
 